# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: huawei_grpc_dialout.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='huawei_grpc_dialout.proto',
  package='huawei_dialout',
  syntax='proto3',
  serialized_pb=_b('\n\x19huawei_grpc_dialout.proto\x12\x0ehuawei_dialout\":\n\x0bserviceArgs\x12\r\n\x05ReqId\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06\x65rrors\x18\x03 \x01(\t2`\n\x0fgRPCDataservice\x12M\n\x0b\x64\x61taPublish\x12\x1b.huawei_dialout.serviceArgs\x1a\x1b.huawei_dialout.serviceArgs\"\x00(\x01\x30\x01\x42\x10\n\x0ehuawei_dialoutb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SERVICEARGS = _descriptor.Descriptor(
  name='serviceArgs',
  full_name='huawei_dialout.serviceArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqId', full_name='huawei_dialout.serviceArgs.ReqId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='huawei_dialout.serviceArgs.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errors', full_name='huawei_dialout.serviceArgs.errors', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['serviceArgs'] = _SERVICEARGS

serviceArgs = _reflection.GeneratedProtocolMessageType('serviceArgs', (_message.Message,), dict(
  DESCRIPTOR = _SERVICEARGS,
  __module__ = 'huawei_grpc_dialout_pb2'
  # @@protoc_insertion_point(class_scope:huawei_dialout.serviceArgs)
  ))
_sym_db.RegisterMessage(serviceArgs)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\016huawei_dialout'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class gRPCDataserviceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.dataPublish = channel.stream_stream(
          '/huawei_dialout.gRPCDataservice/dataPublish',
          request_serializer=serviceArgs.SerializeToString,
          response_deserializer=serviceArgs.FromString,
          )


  class  gRPCDataserviceServicer(object):

    def dataPublish(self, request_iterator, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_gRPCDataserviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'dataPublish': grpc.stream_stream_rpc_method_handler(
            servicer.dataPublish,
            request_deserializer=serviceArgs.FromString,
            response_serializer=serviceArgs.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'huawei_dialout.gRPCDataservice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetagRPCDataserviceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def dataPublish(self, request_iterator, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetagRPCDataserviceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def dataPublish(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()


  def beta_create_gRPCDataservice_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('huawei_dialout.gRPCDataservice', 'dataPublish'): serviceArgs.FromString,
    }
    response_serializers = {
      ('huawei_dialout.gRPCDataservice', 'dataPublish'): serviceArgs.SerializeToString,
    }
    method_implementations = {
      ('huawei_dialout.gRPCDataservice', 'dataPublish'): face_utilities.stream_stream_inline(servicer.dataPublish),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_gRPCDataservice_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('huawei_dialout.gRPCDataservice', 'dataPublish'): serviceArgs.SerializeToString,
    }
    response_deserializers = {
      ('huawei_dialout.gRPCDataservice', 'dataPublish'): serviceArgs.FromString,
    }
    cardinalities = {
      'dataPublish': cardinality.Cardinality.STREAM_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'huawei_dialout.gRPCDataservice', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
